# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Portfolio
    description:  Description
    keywords:     not used by google but by some others
    language:     fr
    robots:       index, follow

  stylesheets:    [main.css ]

  javascripts:    [../sfMultipleAjaxUploadPlugin/js/jquery/jquery-1.3.2.js, ../sfMultipleAjaxUploadPlugin/js/galleriffic/galleriffic.js, ../sfMultipleAjaxUploadPlugin/js/galleriffic/opacityrollover.js]


  has_layout:     true
  layout:         layout

showSuccess:
  stylesheets: [../sfMultipleAjaxUploadPlugin/css/galleriffic/jush.css]
  javascripts: [../sfMultipleAjaxUploadPlugin/js/galleryInstance]
  has_layout:     true
  layout:         layout
